version: "2"

linters:
  default: all

  disable:
    - depguard
    - exhaustruct
    - funcorder
    - godot
    - godox
    - lll
    - revive
    - varnamelen
    - err113
    - wsl
    - wsl_v5
    - noinlineerr
    - noctx

  settings:
    errcheck:
      exclude-functions:
        - (*database/sql.DB).Close
        - (*database/sql.Rows).Close
        - (*database/sql.Stmt).Close

    funlen:
      lines: 150
      statements: 80
    mnd:
      #ignored-functions:
      ignored-numbers:
        - "2"
        - "5"
        - "10"
        - "24"
        - "100"

  exclusions:
    rules:
      - path: internal/usecase/commands/list.go
        text: "Get returns interface"
        linters:
          - ireturn
      - path: internal/usecase/statistic/statistic.go
        linters:
          - nonamedreturns
      - path: internal/infrastructure/adblock/sources.go
        text: "sources is a global variable"
        linters:
          - gochecknoglobals