version: "2"

linters:
  default: all

  disable:
    - depguard
    - exhaustruct
    - funcorder
    - godot
    - godox
    - lll
    - revive
    - varnamelen
    - err113
    - wsl
    - wsl_v5
    - noinlineerr
    - noctx
    - interfacebloat

  settings:
    errcheck:
      exclude-functions:
        - (*database/sql.DB).Close
        - (*database/sql.Rows).Close
        - (*database/sql.Stmt).Close

    funlen:
      lines: 150
      statements: 80

  exclusions:
    rules:
      - path: internal/infrastructure/adblock/sources.go
        text: "sources is a global variable"
        linters:
          - gochecknoglobals