version: "2"

linters:
  default: all

  disable:
    - depguard
    - exhaustruct
    - funcorder
    - ireturn
    - godot
    - godox
    - lll
    - revive
    - varnamelen
    - wsl

  settings:
    funlen:
      lines: 150
      statements: 80
    mnd:
      #ignored-functions:
      ignored-numbers:
        - "2"
        - "5"
        - "10"
        - "24"
        - "100"

  exclusions:
    rules:
      - path: internal/infrastructure/sqlite/user.go
        text: "id out of range"
        linters:
          - err113
      - path: internal/infrastructure/socks5/connection.go
        text: "negative byte count"
        linters:
          - err113
      - path: internal/infrastructure/socks5/authenticator.go
        text: "zero user id returned"
        linters:
          - err113
      - path: internal/usecase/auth/authenticator.go
        text: "userId is not uint32"
        linters:
          - err113
      - path: internal/helper/ttl.go
        text: "empty input"
        linters:
          - err113
      - path: internal/helper/uint32.go
        text: "StringToUint32: invalid digit %q in string"
        linters:
          - err113
      - path: internal/infrastructure/sqlite/
        text: "stmt.Close"
        linters:
          - errcheck
          - staticcheck
      - path: internal/infrastructure/sqlite/
        text: "rows.Close"
        linters:
          - errcheck
          - staticcheck
      - path: internal/infrastructure/socks5/server.go
        text: "Error return value of `l.Close` is not checked"
        linters:
          - errcheck
      - path: internal/usecase/commands/list.go
        text: "Get returns interface"
        linters:
          - ireturn
      - path: internal/usecase/statistic/statistic.go
        linters:
          - nonamedreturns
      - path: internal/infrastructure/adblock/sources.go
        text: "sources"
        linters:
          - gochecknoglobals
      - path: internal/infrastructure/adblock/adblock.go
        linters:
          - errcheck